import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/layout/Header";
import Footer from "@/src/components/layout/Footer";
import { CartProvider } from "@/src/store/cart";
import { AddressProvider } from "@/src/store/address";
import { UserProvider } from "@/src/store/auth";
import { OrderProvider } from "@/src/store/order";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <UserProvider>
          <CartProvider>
            <AddressProvider>
              <OrderProvider>
                <Header />
                <main className="flex-1 w-full pb-14">
                  <div className="max-w-7xl mx-auto px-4">{children}</div>
                </main>
                <Footer />
              </OrderProvider>
            </AddressProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
